### PR TITLE
Start adb if needed

### PR DESCRIPTION
**Pull request by jvoisin**

### CODE REVIEW

**Comment by kpcyrd** [comment]
I don't know if automatically running `adb start-server` is a good idea, in case of a hardware setup I would've probably setup both `adb` and `spytrap-adb` as services independently of each other. If I recall correctly I needed to run `adb` as root on Linux too.

I also don't know how other projects are doing this tho. :/

**Comment by jvoisin** [comment]
One doesn't need to be root on Debian:

```
jvoisin@facilier 22:32 ~ adb start-server 
jvoisin@facilier 22:32 ~ adb kill-server
jvoisin@facilier 22:32 ~ adb start-server 
* daemon not running; starting now at tcp:5037
* daemon started successfully
jvoisin@facilier 22:32 ~ id -n
jvoisin
jvoisin@facilier 22:32 ~ 
```

**Comment by Te-k** [comment]
I think it's easier to launch it automatically. Worst case scenario, the person will have to debug with adb and stop it, but still one less step to do before using it.

**Comment by kpcyrd** [comment]
Sorry for taking some time to look into how `adb start-server` works, I've added a config option, some more error handling and merged it.

Thanks!

**Pull request merged**
