### PR TITLE
Fix the failure of parsing of some multiline settings

### PR DESCRIPTION
**Pull request by tavivat**
Hi,

I was trying this and in one case it was terminating because of failing to parse the output of the settings, so I made this change to make it continue parsing the settings and just log the failing part.

Probably will be better add this error to the "structural logging" for report it properly in the UI.

the case of failure was an app that had a property multi-line ex:

```
    selected_search_engine_chrome={
      "name": "DuckDuckGo",
      "keyword": "duckduckgo.com",
      "search_url": "https://duckduckgo.com/?q={searchTerms}&t=euandroid",
      "suggest_url": "https://duckduckgo.com/ac/?q={searchTerms}&type=list",
      "favicon_url": "https://duckduckgo.com/favicon.ico"
    }
```

### CODE REVIEW

**Comment by kpcyrd** [comment]
hi, thanks for taking the time to look into this! Can you share the Android version and the specific adb command that gave this output? Thanks!

**Comment by tavivat** [comment]
Hi

this come out of `settings list secure` and is on android 12

**Comment by kpcyrd** [comment]
This should be fixed in the latest release, can you try again?

**Comment by tavivat** [comment]
Hi, yes it seems fixed, closing this

**Pull request closed without merging**
